export type Technology =
  | "Next.js"
  | "Tailwind CSS"
  | "Framer Motion"
  | "React Three Fiber"
  | "GSAP"
  | "Lenis"
  | "React"
  | "React Spring"
  | "React Use Gesture"
  | "React Three Cannon"
  | "React Three Drei"
  | "React Three Fiber"
  | "React Three Rapier"
  | "React Three XR"
  | "Lucide React"
  | "Three.js"
  | "TypeScript"
  | "Vite";